name: An NPM Project

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: NPM Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1

      - name: Set up Terrafom
        run: terraform init
